name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -la
          free
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls -la
          free
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Kacper
      - name: Log greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
